### ISSUE TITLE
Enable native lightweight SMPP support in Restcomm

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#207] opened 2015-04-02 19:25 UTC
In many cases Restcomm has to connect to an SMSC over SMPP. Often it is overkill to introduce a full blown SMSC that can translate from SIP to SMPP traffic.

It would reduce Restcomm deployment friction if basic SMPP connectivity is directly supported, without store and forward, retry and other complex delivery modes that are typically handled by an SMSC.

**Comment by gvagenas** [comment] 2015-08-26 08:25
@croufay can we close this issue?

**Comment by deruelle** [comment] 2015-10-08 10:32
Duplicate of https://github.com/Mobicents/RestComm/issues/365

**Closed by deruelle** 2015-10-08 10:32 UTC
Labels: Core engine, Documenting, Integration

**Comment by ivelin** [comment] 2015-10-08 10:39
Yay!!
