### ISSUE TITLE
App forwarding to an Olympus client when a PSTN call comes to the app does not work

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#647] opened 2015-11-14 20:43 UTC
How to reproduce:
1. On cloud.restcomm.com create a new account, with a new registered Olympus client
2. Register a PSTN DID
3. Create an app associated with the DID from step 2 and add Dial logic that simply forwards calls to the registered client.
4. When a call to the PSTN DID is placed, the app does not forward the call to the Olympus client.

See attached video for replay of the problem.

**Comment by ivelin** [comment] 2015-11-14 20:44
https://www.youtube.com/watch?v=pGguvWi8zLA&feature=youtu.be

**Comment by deruelle** [comment] 2016-01-07 14:04
Duplicate of Issue #463. Closing

**Closed** 2016-01-07 14:04 UTC
Labels: 1. Bug, 3. Duplicate, Cloud Ops, Core engine, Mediaserver
